;; Directory for overall customizations
(add-to-list 'load-path "~/.emacs.d/customizations")

;; Directory for language-specific customizations
(add-to-list 'load-path "~/.emacs.d/languages")

;; Directory for utility functions and libraries
(add-to-list 'load-path "~/.emacs.d/libraries")

;; Load overall customizations
(require 'dok-editing)
(require 'dok-navigation)
(require 'dok-ui)
(require 'dok-version-control)

;; Load language-specific customizations
(require 'dok-clojure)
(require 'dok-emacs-lisp)
(require 'dok-haskell)
(require 'dok-html)
(require 'dok-javascript)
(require 'dok-markdown)
(require 'dok-racket)
(require 'dok-shell)
(require 'dok-yaml)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Autogenerated by Emacs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (clj-refactor zenburn-theme powerline company-quickhelp markdown-mode racket-mod racket-mode exec-path-from-shell yaml-mode color-theme-sanityinc-tomorrow intero tagedit smex projectile paredit neotree magit ido-ubiquitous haskell-mode clojure-mode-extra-font-locking cider))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(put 'upcase-region 'disabled nil)
