;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Packages
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(add-to-list 'load-path "~/.emacs.d/customizations")
(add-to-list 'load-path "~/.emacs.d/languages")
(add-to-list 'load-path "~/.emacs.d/libraries")

(require 'package)
(setq package-archives '(("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("gnu" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(when (not package-archive-contents)
 (package-refresh-contents))

;; Manually-downloaded packages will live in the "vendor" directory
(add-to-list 'load-path "~/.emacs.d/vendor")

(defvar my-packages)

(setq my-packages
  '(
    ;; git integration
    magit

    ;; File tree
    neotree

    ;; Transferring the $PATH from my shell to emacs
    exec-path-from-shell
))

;; Install all packages
(dolist (p my-packages)
  (when (not (package-installed-p p))
    (package-install p)))

;; Overall customizations
(require 'dok-editing)
(require 'dok-navigation)
(require 'dok-ui)
(require 'dok-version-control)

;; Language-specific customizations
(require 'dok-clojure)
(require 'dok-emacs-lisp)
(require 'dok-haskell)
(require 'dok-html)
(require 'dok-javascript)
(require 'dok-markdown)
(require 'dok-racket)
(require 'dok-shell)
(require 'dok-yaml)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Startup customizations
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Transfer $PATH from shell to emacs
(exec-path-from-shell-initialize)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Autogenerated by Emacs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (clj-refactor zenburn-theme powerline company-quickhelp markdown-mode racket-mod racket-mode exec-path-from-shell yaml-mode color-theme-sanityinc-tomorrow intero tagedit smex projectile paredit neotree magit ido-ubiquitous haskell-mode clojure-mode-extra-font-locking cider))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(put 'upcase-region 'disabled nil)
